# Generated by Django 5.2.5 on 2025-08-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
